### ISSUE TITLE
How to restore to previous kernel?

### ISSUE THREAD

**Issue by ahxxm** [flar2/ElementalX-N5#1]
:(
Nexus 5 with CM11 nightly build, then i flashed elementalX N5-0.34 on it. 
After flashing CM11 to latest build(from 2014.4.13 to 2014.5.1), it stucks at LOGO while rebooting.
I tried upgrading elementalX from 0.34 to 0.38, it works fine, but it seems still not compatible with latest CM11. (or something wrong with the upgrading process i guess)
So how to restore kernel to CM11 kernel?

**Comment by ahxxm** [comment]
i'm sorry something is missing.
I did the  "elementaxX upgrading" after restore rom from backup. :(

**Comment by flar2** [comment]
reinstall cm11

However, this is not the place to discuss such things.
