### ISSUE TITLE
Nexus 5x dosen't boot with Elemental kernel

### ISSUE THREAD

**Issue by hakong** [flar2/ElementalX-N5#21]
Stock and clean Android 8.1.0, rooted with SuperSU and TWRP 3.2.3-0 installed.
I pushed ElementalX-N5-9.02.zip and installed in TWRP, but the phone boots with the stock kernel (3.10.73-g89fd15db99aa (gcc version 4.9.x-google [...])). Tried with and without clearing the cache, same result.

Any idea?

**Comment by Kronopt** [comment]
You used the wrong kernel.
This is for Nexus 5, not Nexus 5**X**.
You want this [repo](https://github.com/flar2/bullhead)

**Comment by hakong** [comment]
Ah, ofcourse. Works fine with ElementalX-N5X-6.12.
Sorry for the bother!
