### ISSUE TITLE
Flash light turn off when "Max screen off frequency" is set to 1190 Mhz

### ISSUE THREAD

**Issue by ajmtrz** [flar2/ElementalX-N5#6]
Yes, when turn screen off flash light turn off at 2-3 minutes. Only me, or you too? Please check.

**Comment by flar2** [comment]
Most flashlight applications have a timeout set so the battery doesn't drain and the led doesn't burn out.

**Comment by ajmtrz** [comment]
No Aaron, the flashlight is the lollipop status bar menu flashlight button. If screen on flashlight not turn off, when screen off and "max screen off frequency" is set to 2265Mhz flashlight not turn off, but if screen off and "max screen off frequency" is set to default 1190Mhz, flashlight turn off at 2-3 minutes. Confirmed.

**Comment by ajmtrz** [comment]
In my fork i set maxscroff_freq to 2265 as default.

**Comment by ajmtrz** [comment]
Here the real problem:
`<4>[18571.450448] ------------[ cut here ]------------
<4>[18571.450518] WARNING: at kernel/mutex-debug.c:78 debug_mutex_unlock+0x148/0x14c()
<4>[18571.450553] Modules linked in:
<4>[18571.450652] [<c011528c>] (unwind_backtrace+0x0/0x148) from [<c01ab8a0>] (warn_slowpath_null+0x50/0xc8)
<4>[18571.450688] [<c01ab8a0>] (warn_slowpath_null+0x50/0xc8) from [<c0205c78>] (debug_mutex_unlock+0x148/0x14c)
<4>[18571.450755] [<c0205c78>] (debug_mutex_unlock+0x148/0x14c) from [<c0cca0a0>] (__mutex_unlock_slowpath+0xb4/0x1ac)
<4>[18571.450821] [<c0cca0a0>] (__mutex_unlock_slowpath+0xb4/0x1ac) from [<c0883bc8>] (msm_cpp_subdev_ioctl+0x808/0x1cfc)
<4>[18571.450887] [<c0883bc8>] (msm_cpp_subdev_ioctl+0x808/0x1cfc) from [<c0856328>] (msm_close+0xa0/0x1d4)
<4>[18571.450950] [<c0856328>] (msm_close+0xa0/0x1d4) from [<c0898438>] (v4l2_release+0x5c/0x88)
<4>[18571.451011] [<c0898438>] (v4l2_release+0x5c/0x88) from [<c02ac624>] (fput+0xcc/0x264)
<4>[18571.451049] [<c02ac624>] (fput+0xcc/0x264) from [<c02a55cc>] (filp_close+0x6c/0x9c)
<4>[18571.451110] [<c02a55cc>] (filp_close+0x6c/0x9c) from [<c01b0e84>] (put_files_struct+0xbc/0x130)
<4>[18571.451170] [<c01b0e84>] (put_files_struct+0xbc/0x130) from [<c01b13e4>] (do_exit+0x188/0x820)
<4>[18571.451230] [<c01b13e4>] (do_exit+0x188/0x820) from [<c01b1af8>] (do_group_exit+0x48/0xbc)
<4>[18571.451267] [<c01b1af8>] (do_group_exit+0x48/0xbc) from [<c01c25a4>] (get_signal_to_deliver+0x2a8/0x7dc)
<4>[18571.451330] [<c01c25a4>] (get_signal_to_deliver+0x2a8/0x7dc) from [<c01112a4>] (do_signal+0x78/0x538)
<4>[18571.451392] [<c01112a4>] (do_signal+0x78/0x538) from [<c0111ab8>] (do_notify_resume+0x68/0x6c)
<4>[18571.451453] [<c0111ab8>] (do_notify_resume+0x68/0x6c) from [<c010ddd8>] (work_pending+0x24/0x28)
<4>[18571.451486] ---[ end trace 1e8293096a2d21fb ]---
<3>[18571.451652] msm_cci_release invalid ref count 0 / cci state 1
<3>[18571.451685] msm_sensor_cci_i2c_util line 502 rc = -22
<3>[18571.451743] msm_eeprom_close cci_init failed
<3>[18571.451864] msm_isp_close_node: Invalid close
<3>[18571.454470] msm_ispif_release: ispif invalid state 1
<4>[18571.469730] done.
<4>[18571.481969] Freezing user space processes ... (elapsed 0.001 seconds) done.
<4>[18571.483998] Freezing remaining freezable tasks ... (elapsed 0.001 seconds) done.
<4>[18571.485653] Suspending console(s) (use no_console_suspend to debug)
<6>[18571.558601] active wakeup source: alarm
<3>[18571.558632] PM: Some devices failed to suspend
<6>[18571.638092] PM: resume of devices complete after 79.432 msecs
<4>[18571.646458] Restarting tasks ... done
`
